### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'parse_table'

### ISSUE THREAD

**Issue by hwhsu1231** [PhuNH/hugo-gettext#1]
### Problem Description

I tried to test how `hugo-gettext` works with those Hugo-based documentation (for example, [graphviz](https://gitlab.com/graphviz/graphviz.gitlab.io)), but encountered this error when running `hugo-gettext extract pot`:

```
Traceback (most recent call last):
  File "C:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python310\Scripts\hugo-gettext.exe\__main__.py", line 7, in <module>
  File "C:\Python\Python310\lib\site-packages\hugo_gettext\cli.py", line 41, in main
    args.func(args)
  File "C:\Python\Python310\lib\site-packages\hugo_gettext\extraction\index.py", line 83, in extract
    hg_config, mdi = initialize(RendererHugoI18N, args.customs, args.config)
  File "C:\Python\Python310\lib\site-packages\hugo_gettext\config.py", line 231, in initialize
    if hg_config.parse_table:
AttributeError: 'Config' object has no attribute 'parse_table'
```

The full log is as follows:

<details><summary>Click to expand the log</summary>

```cmd
D:\Test>git clone https://gitlab.com/graphviz/graphviz.gitlab.io.git
Cloning into 'graphviz.gitlab.io'...
remote: Enumerating objects: 12083, done.
remote: Counting objects: 100% (722/722), done.
remote: Compressing objects: 100% (315/315), done.
remote: Total 12083 (delta 406), reused 618 (delta 333), pack-reused 11361
Receiving objects: 100% (12083/12083), 171.75 MiB | 10.62 MiB/s, done.
Resolving deltas: 100% (6569/6569), done.
Updating files: 100% (1220/1220), done.

D:\Test>cd graphviz.gitlab.io

D:\Test\graphviz.gitlab.io>hugo-gettext extract pot
Traceback (most recent call last):
  File "C:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python310\Scripts\hugo-gettext.exe\__main__.py", line 7, in <module>
  File "C:\Python\Python310\lib\site-packages\hugo_gettext\cli.py", line 41, in main
    args.func(args)
  File "C:\Python\Python310\lib\site-packages\hugo_gettext\extraction\index.py", line 83, in extract
    hg_config, mdi = initialize(RendererHugoI18N, args.customs, args.config)
  File "C:\Python\Python310\lib\site-packages\hugo_gettext\config.py", line 231, in initialize
    if hg_config.parse_table:
AttributeError: 'Config' object has no attribute 'parse_table'

D:\Test\graphviz.gitlab.io>
```

</details>

### Versions and Platforms

* OS: `Windows 11`
* python: `3.10.7`
* hugo-gettext: `0.6.0`

**Comment by PhuNH** [comment]
Apologies for my late response.

Not sure if this is still relevant and useful for you, but let me just give you an answer: the issue is that an `i18n` config block is required in your Hugo config file, and it seemed to be missing. You need to add such a block to tell hugo-gettext about how you want it to process your Hugo project.

I've made [a fix](https://invent.kde.org/websites/hugo-gettext/-/merge_requests/4) for this. With the fix, you will see a clear error that such a config block is required, not this `AttributeError`.

The development of this project is now in https://invent.kde.org/websites/hugo-gettext/
